config-version: 1
enabled: true

apply:
  chat-display-name: true
  tab-list-name: true

above-head:
  mode: "text-display"
  hide-vanilla-name: true
  y-offset: 2.25
  update-interval-ticks: 2
  view-range: 64.0
  shadowed: true
  see-through: false
  default-background: false

scoreboard:
  override-existing-teams: false

validation:
  allow-minimessage: true
  allow-spaces: true
  min-plain-length: 1
  max-plain-length: 32

