config-version: 2

enabled: true

movement:
  speed: 0.2
  arrival-distance: 1.5
  tick-interval: 2
  wander-radius: 10

behavior:
  invulnerable: false
  gravity: true
  immovable: false

skins:
  folder: "skins"
  default: "default"
